Process stop/start test program
tiagoshibata/pcs3746-sistemas-operacionais pull request #6
Opened 2017-06-11 22:12 UTC by tiagoshibata

2017-06-11 23:18 UTC, EpicEric requested changes
Dúvida sobre forking e pedido de alteração de nome de variável.

2017-06-11 23:18 UTC, EpicEric commented on 2/initramfs/init.c
> +static const char * const programs[] = { "/stop_test" };
Ele vai executar um fork dentro do fork então?

2017-06-11 23:18 UTC, EpicEric commented on 2/initramfs/stop.h
> +long stop_process(int fd)
Não é melhor pid ao invés de fd, já que é o usado no kernel?

2017-06-11 23:29 UTC, EpicEric reviewed
Dúvida sobre forking e pedido de alteração de nome de variável.

2017-06-12 00:17 UTC, tiagoshibata commented on 2/initramfs/init.c
> +static const char * const programs[] = { "/stop_test" };
É, não vejo problema... Vai ser um filho do `init` rodando o teste.

2017-06-12 00:19 UTC, tiagoshibata commented on 2/initramfs/stop.h
> +long stop_process(int fd)
Sim, foi no copy-paste esse :)

2017-06-12 00:20 UTC, merged